# Generated by Django 5.1.4 on 2024-12-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcsNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acs_id",
                    models.IntegerField(unique=True, verbose_name="ID конференции"),
                ),
                (
                    "number",
                    models.IntegerField(unique=True, verbose_name="Номер конференции"),
                ),
                ("password", models.IntegerField(verbose_name="ПИН-код конференции")),
            ],
        ),
    ]
