# Generated by Django 5.1.4 on 2024-12-09 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audioconf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acsnumber",
            name="acs_id",
            field=models.IntegerField(
                help_text="ID конференции на АКСС",
                unique=True,
                verbose_name="ID конференции",
            ),
        ),
        migrations.AlterField(
            model_name="acsnumber",
            name="number",
            field=models.IntegerField(
                help_text="5-значный номер внутренний",
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(33300),
                    django.core.validators.MaxValueValidator(33399),
                ],
                verbose_name="Номер конференции",
            ),
        ),
        migrations.AlterField(
            model_name="acsnumber",
            name="password",
            field=models.IntegerField(
                help_text="ПИН-код от номера на АКСС",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="ПИН-код конференции",
            ),
        ),
    ]
