# Generated by Django 5.1.4 on 2024-12-09 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audioconf", "0002_alter_acsnumber_acs_id_alter_acsnumber_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcsPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acs_id",
                    models.IntegerField(
                        help_text="ID конференции на АКСС",
                        unique=True,
                        verbose_name="ID конференции",
                    ),
                ),
                (
                    "phone",
                    models.IntegerField(
                        help_text="5-значный внутренний номер",
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(33300),
                            django.core.validators.MaxValueValidator(33399),
                        ],
                        verbose_name="Номер конференции",
                    ),
                ),
                (
                    "password",
                    models.IntegerField(
                        help_text="ПИН-код от номера на АКСС",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                        verbose_name="ПИН-код конференции",
                    ),
                ),
            ],
            options={
                "verbose_name": "АКС Номер",
                "verbose_name_plural": "АКС Номера",
            },
        ),
        migrations.DeleteModel(
            name="AcsNumber",
        ),
    ]
