# Generated by Django 5.1.4 on 2024-12-09 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioconf', '0003_acsphone_delete_acsnumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_conf', models.DateTimeField(verbose_name='Время начала конференции')),
                ('end_conf', models.DateTimeField(verbose_name='Время окончания конференции')),
            ],
            options={
                'default_related_name': 'bookings',
            },
        ),
        migrations.AlterModelOptions(
            name='acsphone',
            options={'default_related_name': 'acs_phones', 'verbose_name': 'АКС Номер', 'verbose_name_plural': 'АКС Номера'},
        ),
        migrations.AddConstraint(
            model_name='acsphone',
            constraint=models.UniqueConstraint(fields=('acs_id', 'phone'), name='Ограничение по уникальному номеру АКС'),
        ),
        migrations.AddField(
            model_name='bookingacs',
            name='acs_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioconf.acsphone', verbose_name='АКС Номер'),
        ),
        migrations.AddField(
            model_name='bookingacs',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец бронирования'),
        ),
        migrations.AddConstraint(
            model_name='bookingacs',
            constraint=models.CheckConstraint(condition=models.Q(('start_conf__lt', models.F('end_conf'))), name='Начало до окончания'),
        ),
    ]
