# Generated by Django 5.1.4 on 2024-12-10 07:47

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audioconf", "0004_bookingacs_alter_acsphone_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingacs",
            options={
                "default_related_name": "bookings",
                "ordering": ("start_conf", "end_conf", "acs_phone"),
                "verbose_name": "Бронь АКС номера",
                "verbose_name_plural": "Бронирования АКС номеров",
            },
        ),
        migrations.RemoveConstraint(
            model_name="bookingacs",
            name="Начало до окончания",
        ),
        migrations.AddConstraint(
            model_name="bookingacs",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_conf__lt", models.F("end_conf"))),
                name="Время начало бронирования после времени окончания",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingacs",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "start_conf__gt",
                        datetime.datetime(2024, 12, 10, 10, 47, 46, 400529),
                    )
                ),
                name="Время начала бронирование в прошлом",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingacs",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_conf__date", models.F("end_conf__date"))),
                name="Бронирование заканчивается в следующий день",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingacs",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(
                            ("acs_phone", models.F("acs_phone")),
                            (
                                "start_conf__range",
                                (models.F("start_conf"), models.F("end_conf")),
                            ),
                        ),
                        (
                            "end_conf__range",
                            (models.F("start_conf"), models.F("end_conf")),
                        ),
                        _connector="OR",
                    )
                ),
                name="Пересечение бронирований",
            ),
        ),
    ]
