# Generated by Django 5.1.4 on 2024-12-10 08:11

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audioconf", "0005_alter_bookingacs_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookingacs",
            name="Время начала бронирование в прошлом",
        ),
        migrations.RemoveConstraint(
            model_name="bookingacs",
            name="Пересечение бронирований",
        ),
        migrations.AddConstraint(
            model_name="bookingacs",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "start_conf__gt",
                        datetime.datetime(2024, 12, 10, 11, 11, 56, 22596),
                    )
                ),
                name="Время начала бронирование в прошлом",
            ),
        ),
    ]
