# Generated by Django 5.1.4 on 2024-12-20 07:53

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioconf', '0006_remove_bookingacs_время_начала_бронирование_в_прошлом_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingacs',
            name='Время начала бронирование в прошлом',
        ),
        migrations.AddConstraint(
            model_name='bookingacs',
            constraint=models.CheckConstraint(condition=models.Q(('start_conf__gt', datetime.datetime(2024, 12, 20, 10, 53, 17, 981851))), name='Время начала бронирование в прошлом'),
        ),
    ]
