# Generated by Django 5.1.4 on 2025-01-06 17:30

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioconf', '0007_remove_bookingacs_время_начала_бронирование_в_прошлом_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingacs',
            name='Время начала бронирование в прошлом',
        ),
        migrations.AddField(
            model_name='bookingacs',
            name='responsible',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Ответственный за бронирование'),
        ),
        migrations.AddConstraint(
            model_name='bookingacs',
            constraint=models.CheckConstraint(condition=models.Q(('start_conf__gt', datetime.datetime(2025, 1, 6, 20, 30, 44, 141280))), name='Время начала бронирование в прошлом'),
        ),
    ]
