# Generated by Django 5.1.4 on 2025-01-07 09:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioconf', '0008_remove_bookingacs_время_начала_бронирование_в_прошлом_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'default_related_name': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'default_related_name': 'employees',
            },
        ),
        migrations.RemoveConstraint(
            model_name='bookingacs',
            name='Время начала бронирование в прошлом',
        ),
        migrations.AddConstraint(
            model_name='bookingacs',
            constraint=models.CheckConstraint(condition=models.Q(('start_conf__gt', datetime.datetime(2025, 1, 7, 12, 37, 36, 612244))), name='Время начала бронирование в прошлом'),
        ),
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audioconf.department'),
        ),
    ]
