# Generated by Django 5.1.4 on 2025-01-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioconf', '0011_alter_department_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'default_related_name': 'departments', 'ordering': ('id', 'name'), 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'default_related_name': 'employees', 'ordering': ('last_name', 'first_name', 'middle_name'), 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='acsphone',
            name='department',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audioconf.department'),
        ),
    ]
