# Generated by Django 5.1.4 on 2025-01-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioconf', '0012_alter_department_options_alter_employees_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acsphone',
            options={'default_related_name': 'acs_phones', 'ordering': ('phone', 'acs_id'), 'verbose_name': 'АКС Номер', 'verbose_name_plural': 'АКС Номера'},
        ),
        migrations.AddField(
            model_name='department',
            name='is_superdepartment',
            field=models.BooleanField(default=False, verbose_name='Суперподразделение'),
        ),
    ]
