# Generated by Django 5.1.4 on 2025-02-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioconf', '0013_alter_acsphone_options_department_is_superdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingacs',
            name='record',
            field=models.BooleanField(default=False, verbose_name='Предоставить запись'),
        ),
    ]
