volumes:
  pg_data:
  static:
  media:
  acs_info:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./portal_conf/
    env_file: .env
    volumes:
      - static:/static
      - media:/media
      - acs_info:/data
    depends_on:
      - db
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
