volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: ${IMAGE_OWNER}/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  gateway:
    image: ${IMAGE_OWNER}/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend